### ISSUE TITLE
printer stops/freezes when printing from serial mode

### ISSUE THREAD

**Issue by brasco901** [bigtreetech/BIGTREETECH-TFT35-V3.0#18]
Prints stop/freeze when printing from serial/touchscreen mode.  everything works fine on lcd12864 mode. any ideas?

**Comment by dziabi3** [comment]
I have a very similar problem.
The printer stops at 87% progress.
When the printer completes the printout, it goes to the TFT mode selection screen (marlin - bigtreetech).
Sometimes FRO also changes by itself.
Bardzoc often doesn't have a touch screen or works with a long delay.

I plan to return to the original ender 3 disc, because I can not trust the skr mini e3 V1.2 and tft35 e3 V3.0 discs. It seems to me that the original ender 3 disc provided better edge quality (I played with the Linear Advance function and I don't see any benefit in it).

**Comment by Dosi-Innovate** [comment]
Same Issue here did you guys resolve this?
